<?php

use MF\Model\Container;

$this->view->message = Container::getModel('message');
$this->view->flassMessage = $this->view->message->getMessage();

?>

<section id="form">
    <div class="container">
        <div class="row">
            <div class="col-sm-5">
                <div class="login-form text-center">
                    <h2>Entre na sua Conta</h2>
                    <form action="/auth/login" method="POST">
                        <input type="email" name="email" placeholder="Endereço de E-mail" >
                        <input type="password" name="password" placeholder="Senha" >
                        <button type="submit" class="btn btn-default text-center">Entrar</button>
                    </form>
                </div>
            </div>
            <div class="col-sm-2"></div>
            <div class="col-sm-5">
                <div class="signup-form text-center">
                    <h2>Cadastre sua conta</h2>
                    <form action="/auth/register" method="POST">
                        <input type="text" name="username" placeholder="Usuario" />
                        <input type="email" name="email" placeholder="Endereço de E-mail" >
                        <input type="email" name="emailConfirm" placeholder="Confirme seu E-mail" >
                        <input type="password" name="password" placeholder="Senha" >
                        <input type="password" name="passwordConfirm" placeholder="Confirme sua Senha" >
                        <button type="submit" class="btn btn-default text-center">Registrar</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>
	
<?php if(!empty($this->view->flassMessage)){ ?>
    <div class="msg-container">
        <p class="msg <?php echo $this->view->flassMessage['type'] ?>">
            <?php echo $this->view->flassMessage['msg'] ?>
        </p>
    </div>
<?php }  ?>

<?php

    if(!empty($this->view->flassMessage['msg'])){
        $this->view->message->clearMessage();
    }


?>
