<div class="container text-center">
    <div class="logo-404">
        <a href="/"><img src="images/home/logo.png" alt="" /></a>
    </div>
    <div class="content-404">
        <img src="img/404/404.png" class="img-responsive" alt="" />
        <h1><b>OPPS!</b> Essa pagina não existe</h1>
        <p>Para não ficar travado em uma página sem função e inexistente</p>
        <h2><a href="/">Clique aqui e volte para o inicio ^-^</a></h2>
    </div>
</div>