<div class="col-sm-2" id="categoty" style="min-height: 0!important;">
    <div class="wrapper">
        <nav id="sidebar">
            <div class="sidebar-header text-center">
                <h3>Categorias</h3>
            </div>
            <ul class="list-unstyled components">
                <li class="active">
                    <a href="#homeSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Camisas</a>
                    <ul class="collapse list-unstyled text-light" id="homeSubmenu">
                        <li class="text-light">
                            <a href="#" class="text-light">Home 1</a>
                        </li>
                        <li class="text-light">
                            <a href="#" class="text-light">Home 2</a>
                        </li>
                        <li class="text-light">
                            <a href="#" class="text-light">Home 3</a>
                        </li>
                    </ul>
                </li>

            </ul>
        </nav>
    </div>
</div>