<!-- <footer id="footer">
    <div class="offset-sm-2 col-sm-8">
        <div class="container" style="max-width: 1100px!important;">
            <div class="footer-widget">
                <div class="container" style="max-width: 1100px!important;">
                    <div class="col-sm-2">
                        <div class="single-widget">
                            <h2>Serviços</h2>
                            <ul class="nav nav-pills nav-stacked">
                                <li><a href="#">Ajuda Online</a></li>
                                <li><a href="#">Entre em contato</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-sm-2">
                        <div class="single-widget">
                            <h2>Politicas</h2>
                            <ul class="nav nav-pills nav-stacked">
                                <li><a href="#">Termos de Uso</a></li>
                                <li><a href="#">Politica de Privacidade</a></li>
                                <li><a href="#">Politica de Segurança</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-sm-2">
                        <div class="single-widget">
                            <h2>Sobre Nós</h2>
                            <ul class="nav nav-pills nav-stacked">
                                <li><a href="#">Informações da companhia</a></li>
                                <li><a href="#">Localização</a></li>
                                <li><a href="#">Copyright</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-sm-3 col-sm-offset-1">
                        <div class="single-widget">
                            <h2>Notificações</h2>
                            <form action="#" class="searchform">
                                <input type="text" placeholder="Seu endereço de E-mail" name="email" />
                                <button type="submit" class="btn btn-default"><i class="fa fa-arrow-circle-o-right"></i></button>
                                <p>Para receber informações em primeira mão</p>
                            </form>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>

</footer> -->