<?php

    use MF\Model\Container;

    $user = Container::getModel('user');
    $user->__set('id', $_SESSION['id']);
    $user->__set('perfil', $user->getImage());

?>

<header class="topbar" data-navbarbg="skin5">
    <nav class="navbar top-navbar navbar-expand-md navbar-dark">
        <div class="navbar-header" data-logobg="skin6">
            <a class="navbar-brand" href="/">
                <b class="logo-icon">
                    <img src="/plugins/images/logo-icon.png" alt="homepage" />
                </b>
                <span class="logo-text">
                    <img src="/plugins/images/logo2.png" alt="homepage" />
                </span>
            </a>
        </div>
        <div class="navbar-collapse collapse" id="navbarSupportedContent" data-navbarbg="skin5">

            <ul class="navbar-nav ms-auto d-flex align-items-center">

                <li class=" in">
                    <form role="search" class="app-search d-none d-md-block me-3">
                        <input type="text" placeholder="Search..." class="form-control mt-0">
                        <a href="" class="active">
                            <i class="fa fa-search"></i>
                        </a>
                    </form>
                </li>
                <li class="adminItem">
                    <a href="#notficação">
                        <i class="fa-solid fa-bell"></i>Notificações
                    </a>
                </li>
                <li>
                    <a href="#" class="profile-pic">

                        <img src="/img/profiles/<?php echo empty($user->__get('perfil')) ? 'noUser.png':$user->__get('perfil') ?>" width="36" class="img-circle">

                        <span class="text-white font-medium"><?php echo $_SESSION['username'] ?></span>
                    </a>
                </li>
                <li class="adminItem logout" style="margin-right: 3rem;">
                    <a href="/logout">
                        <i class="fa fa-times"></i>Sair
                    </a>
                </li>
            </ul>
        </div>
    </nav>
</header>