<aside class="left-sidebar" data-sidebarbg="skin6">
    <div class="scroll-sidebar">
        <nav class="sidebar-nav">
            <ul id="sidebarnav">
                
                <li class="sidebar-item pt-2" id="admin">
                    <a class="sidebar-link waves-effect waves-dark sidebar-link" href="/adminConfig" aria-expanded="false">
                        <i class="far fa-clock" aria-hidden="true"></i>
                        <span class="hide-menu">Home</span>
                    </a>
                </li>
                <li class="sidebar-item pt-2" id="profile">
                    <a class="sidebar-link waves-effect waves-dark sidebar-link" href="/profile" aria-expanded="false">
                        <i class="fa fa-user" aria-hidden="true"></i>
                        <span class="hide-menu">Profile</span>
                    </a>
                </li>
                <li class="sidebar-item pt-2" id="message">
                    <a class="sidebar-link waves-effect waves-dark sidebar-link" href="/adminConfig/messages" aria-expanded="false">
                        <i class="fa-solid fa-comment" aria-hidden="true"></i>
                        <span class="hide-menu">Mensagens</span>
                    </a>
                </li>
                
            </ul>
        </nav>
    </div>
</aside>