<!-- CLEAR MESSAGE -->
<?php

	use MF\Model\Container;

	$this->view->message = Container::getModel('message');
	$this->view->flassMessage = $this->view->message->getMessage();

	if (!empty($this->view->flassMessage['msg'])) {
		$this->view->message->clearMessage();
	}


?>

<!DOCTYPE html>
<html lang="pt-br">

<head>
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta charset="utf-8">

	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css">
	<link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous" />
	<link rel="stylesheet" type="text/css" href="/css/style.css">
	<link href="css/bootstrap.min.css" rel="stylesheet">
	<link href="/css/font-awesome.min.css" rel="stylesheet">
	<link href="/css/prettyPhoto.css" rel="stylesheet">
	<link href="/css/price-range.css" rel="stylesheet">
	<link href="/css/animate.css" rel="stylesheet">
	<link href="/css/main.css" rel="stylesheet">
	<link href="/css/responsive.css" rel="stylesheet">
	<link href="/css/style.css" rel="stylesheet">

	<link rel="shortcut icon" href="#" type="image/x-icon">

	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous">
	</script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous">
	</script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous">
	</script>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous">
	</script>
	<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous">
	</script>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous">
	</script>
	<script src="/js/jquery.js"></script>
	<script src="/js/jquery.scrollUp.min.js"></script>
	<script src="/js/bootstrap.min.js"></script>
	<script src="/js/main.js"></script>
	<script src="/js/html5shiv.js"></script>

	<title>E-Commerce | <?php echo $this->view->page ?> |</title>

</head>


<body onscroll="mudarMenu()">

	<!-- SIDEBAR & CATEGORY NAV -->
	<div class="content-wrapper">
		<div class="row">
			<!-- CATEGORY NAV -->
			<?php $this->loadComponents('category') ?>
			<!-- SIDEBAR -->
            <div class="col-sm-10 position-fixed" style="right: .2rem;z-index: 999!important;">
			    <?php $this->loadComponents('sidebar') ?>
            </div>
		</div>
	</div>
	
	<!-- SPACING -->
	<br><br><br><br>

	<!-- CONTET -->
	<div class="content-wrapper p-5" id="main-container">
		<div class="offset-sm-2 p-5">
			<?= $this->content() ?>
		</div>
	</div>

	<!-- FOOTER -->
	<?php $this->loadComponents('footer') ?>

	<!-- MESSAGE -->
	<?php 

		// var_dump($_SESSION);
	
	?>
	<?php if (!empty($this->view->flassMessage)) { ?>
		<div class="msg-container">
			<p class="msg <?php echo $this->view->flassMessage['type'] ?>">
				<?php echo $this->view->flassMessage['msg'] ?>
			</p>
		</div>
	<?php }  ?>
</body>

</html>