<div class="page-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12 col-lg-10 col-sm-12">
                <div class="card white-box p-0">
                    <div class="card-body">
                        <h3 class="box-title mb-0">Recent Comments</h3>
                    </div>
                    <?php $this->loadComponents('messages') ?>
                </div>
            </div>
        </div>
    </div>
    
</div>
</div>